name: flutter_logout_filestore
description: added logout and filestore
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.4

  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter

  flutter_redux: ^0.9.0

  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13






dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  very_good_analysis: ^2.4.0


